Abysmiler
life-studied/douyin-simple pull request #13
Opened 2023-08-22 10:37 UTC by Abysmiler

完成controller层，dao层和service层大致函数的书写

2023-08-22 12:09 UTC, life-studied commented on Go-Project/controller/common.go
> +// RollbackTransaction 回滚事务
醉梦说他给出了全局的统一DB接口，你和他商量一下怎么说

2023-08-22 12:10 UTC, life-studied commented on Go-Project/dao/comment.go
这里也是，最好能用一个接口，减少冗余

2023-08-22 12:11 UTC, life-studied commented on Go-Project/dao/common.go
在global里面有一个全局DB

2023-08-22 12:11 UTC, life-studied commented on Go-Project/service/CommentService.go
这里和上面的代码有关联，需要一起改

2023-08-22 12:13 UTC, life-studied commented on Go-Project/controller/comment.go
这里与下面的问题修改需要一起改

2023-08-22 12:13 UTC, life-studied requested changes
主要问题是DB接口冗余，跟醉梦商量一下如何处理

2023-08-23 04:03 UTC, Abysmiler commented
> 
已经更改了DB接口，并做了一些小部分代码的修改

2023-08-23 07:23 UTC, closed without merging